title: Oinam
baseurl: ""
url: "https://oinam.com"

permalink: pretty
permalink: /:title/

sass:
  style: compressed
  sourcemap: never

exclude:
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*